export const cartItems = [
    {
        imgSrc: 'https://coldxdev.github.io/images/products/product-1.jpg',
        name: 'Graystone vase',
        desc: 'A timeless ceramic vase with a tri color grey glaze.',
        price: '£85',
        id: 1,
    },
    {
        imgSrc: 'https://coldxdev.github.io/images/products/product-2.jpg',
        name: 'Basic white vase',
        desc: 'Beautiful and simple this is one for the classics',
        price: '£285',
        id: 2,
    }, {
        imgSrc: 'https://coldxdev.github.io/images/products/product-1.jpg',
        name: 'Graystone vase',
        desc: 'A timeless ceramic vase with a tri color grey glaze.',
        price: '£85',
        id: 3,
    },
    {
        imgSrc: 'https://coldxdev.github.io/images/products/product-2.jpg',
        name: 'Basic white vase',
        desc: 'Beautiful and simple this is one for the classics',
        price: '£285',
        id: 4,
    }, {
        imgSrc: 'https://coldxdev.github.io/images/products/product-1.jpg',
        name: 'Graystone vase',
        desc: 'A timeless ceramic vase with a tri color grey glaze.',
        price: '£85',
        id: 5,
    },
    {
        imgSrc: 'https://coldxdev.github.io/images/products/product-2.jpg',
        name: 'Basic white vase',
        desc: 'Beautiful and simple this is one for the classics',
        price: '£285',
        id: 6,
    }, {
        imgSrc: 'https://coldxdev.github.io/images/products/product-1.jpg',
        name: 'Graystone vase',
        desc: 'A timeless ceramic vase with a tri color grey glaze.',
        price: '£85',
        id: 7,
    },
    {
        imgSrc: 'https://coldxdev.github.io/images/products/product-2.jpg',
        name: 'Basic white vase',
        desc: 'Beautiful and simple this is one for the classics',
        price: '£285',
        id: 8,
    }, {
        imgSrc: 'https://coldxdev.github.io/images/products/product-1.jpg',
        name: 'Graystone vase',
        desc: 'A timeless ceramic vase with a tri color grey glaze.',
        price: '£85',
        id: 9,
    },
    {
        imgSrc: 'https://coldxdev.github.io/images/products/product-2.jpg',
        name: 'Basic white vase',
        desc: 'Beautiful and simple this is one for the classics',
        price: '£285',
        id: 10,
    }, {
        imgSrc: 'https://coldxdev.github.io/images/products/product-1.jpg',
        name: 'Graystone vase',
        desc: 'A timeless ceramic vase with a tri color grey glaze.',
        price: '£85',
        id: 11,
    },
    {
        imgSrc: 'https://coldxdev.github.io/images/products/product-2.jpg',
        name: 'Basic white vase',
        desc: 'Beautiful and simple this is one for the classics',
        price: '£285',
        id: 12,
    }, {
        imgSrc: 'https://coldxdev.github.io/images/products/product-1.jpg',
        name: 'Graystone vase',
        desc: 'A timeless ceramic vase with a tri color grey glaze.',
        price: '£85',
        id: 13,
    },
    {
        imgSrc: 'https://coldxdev.github.io/images/products/product-2.jpg',
        name: 'Basic white vase',
        desc: 'Beautiful and simple this is one for the classics',
        price: '£285',
        id: 14,
    }, {
        imgSrc: 'https://coldxdev.github.io/images/products/product-1.jpg',
        name: 'Graystone vase',
        desc: 'A timeless ceramic vase with a tri color grey glaze.',
        price: '£85',
        id: 15,
    },
    {
        imgSrc: 'https://coldxdev.github.io/images/products/product-2.jpg',
        name: 'Basic white vase',
        desc: 'Beautiful and simple this is one for the classics',
        price: '£285',
        id: 16,
    },
]